### ISSUE TITLE
Is it okay to include part of gist in MIT licensed project?

### ISSUE THREAD

**Issue by michael-dewar** [michael-dewar/shinyauthr#1]
Hello @calligross,

I really liked your Gist (https://gist.github.com/calligross/e779281b500eb93ee9e42e4d72448189)  about cookie-based authentication for Shiny apps.  I want to use this idea in a pull request that I am preparing for someone else's project.  This other project has an MIT license.  Is it okay to use part of your work in this way?

Original project: https://github.com/PaulC91/shinyauthr
My modification: https://github.com/michael-dewar/shinyauthr

Thanks!

**Comment by calligross** [comment]
Sure, no problem at all.

If you are interested in another, more professional approach, I can recommend you the following solution. We used this in a couple of projects now and it works like a charm, especially if you are getting your data from an REST API.

In general you also could:
1. Setup Keycloak (Keycloak.org)
2. Include the javascript Keycloak client (it is part of the Keycloak installation)
3. Pass the token to your shiny session
4. use the refresh part of the token to renew it with httr to get a httr oauth token

**Comment by michael-dewar** [comment]
Great, thanks a lot!  Keycloak looks really interesting.  I'll check it out.

Thanks again!
